### ISSUE TITLE
OutOfRangeError Occurred

### ISSUE THREAD

**Issue by ShaneTsui** [zhengyang-wang/Deeplab-v2--ResNet-101--Tensorflow#21]
Hi, there. I came across an out-of-range error after executing the instruction: `python main.py`

Here's some of my configuration:
> OS: Windows 10
> python: 3.5 ( not Anaconda )
> Tensorflow: 1.3 + CPU

Would you please help me with this? Thanks!

===================================================================

2017-12-28 09:50:03.044001: W C:\tf_jenkins\home\workspace\rel-win\M\windows\PY\35\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2017-12-28 09:50:03.044142: W C:\tf_jenkins\home\workspace\rel-win\M\windows\PY\35\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
-----------build encoder: deeplab pre-trained-----------
after start block: (10, 81, 81, 64)
after block1: (10, 81, 81, 256)
after block2: (10, 41, 41, 512)
after block3: (10, 41, 41, 1024)
after block4: (10, 41, 41, 2048)
-----------build decoder-----------
after aspp block: (10, 41, 41, 21)
Restored model parameters from ../reference model/deeplab_resnet_init.ckpt
2017-12-28 09:50:44.847421: W C:\tf_jenkins\home\workspace\rel-win\M\windows\PY\35\tensorflow\core\framework\op_kernel.cc:1192] Not found: NewRandomAccessFile failed to Create/Open: E:\Data\VOC_data\VOC\VOCdevkit\VOC2012/SegmentationClassAug/2008_003519.png : 系统找不到指定的路径。

Traceback (most recent call last):
  File "C:\Program Files\Python 3.5\lib\site-packages\tensorflow\python\client\session.py", line 1327, in _do_call
    return fn(*args)
  File "C:\Program Files\Python 3.5\lib\site-packages\tensorflow\python\client\session.py", line 1306, in _run_fn
    status, run_metadata)
  File "C:\Program Files\Python 3.5\lib\contextlib.py", line 66, in __exit__
    next(self.gen)
  File "C:\Program Files\Python 3.5\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.OutOfRangeError: FIFOQueue '_1_create_inputs/batch/fifo_queue' is closed and has insufficient elements (requested 10, current size 0)
         [[Node: create_inputs/batch = QueueDequeueManyV2[component_types=[DT_FLOAT, DT_UINT8], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](create_inputs/batch/fifo_queue, create_inputs/batch/n)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 82, in <module>
    tf.app.run()
  File "C:\Program Files\Python 3.5\lib\site-packages\tensorflow\python\platform\app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "main.py", line 76, in main
    getattr(model, args.option)()
  File "C:\Users\Shane\Desktop\Deeplab-v2--ResNet-101--Tensorflow\model.py", line 60, in train
    feed_dict=feed_dict)
  File "C:\Program Files\Python 3.5\lib\site-packages\tensorflow\python\client\session.py", line 895, in run
    run_metadata_ptr)
  File "C:\Program Files\Python 3.5\lib\site-packages\tensorflow\python\client\session.py", line 1124, in _run
    feed_dict_tensor, options, run_metadata)
  File "C:\Program Files\Python 3.5\lib\site-packages\tensorflow\python\client\session.py", line 1321, in _do_run
    options, run_metadata)
  File "C:\Program Files\Python 3.5\lib\site-packages\tensorflow\python\client\session.py", line 1340, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.OutOfRangeError: FIFOQueue '_1_create_inputs/batch/fifo_queue' is closed and has insufficient elements (requested 10, current size 0)
         [[Node: create_inputs/batch = QueueDequeueManyV2[component_types=[DT_FLOAT, DT_UINT8], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](create_inputs/batch/fifo_queue, create_inputs/batch/n)]]

Caused by op 'create_inputs/batch', defined at:
  File "main.py", line 82, in <module>
    tf.app.run()
  File "C:\Program Files\Python 3.5\lib\site-packages\tensorflow\python\platform\app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "main.py", line 76, in main
    getattr(model, args.option)()
  File "C:\Users\Shane\Desktop\Deeplab-v2--ResNet-101--Tensorflow\model.py", line 36, in train
    self.train_setup()
  File "C:\Users\Shane\Desktop\Deeplab-v2--ResNet-101--Tensorflow\model.py", line 169, in train_setup
    self.image_batch, self.label_batch = reader.dequeue(self.conf.batch_size)
  File "C:\Users\Shane\Desktop\Deeplab-v2--ResNet-101--Tensorflow\utils\image_reader.py", line 179, in dequeue
    num_elements)
  File "C:\Program Files\Python 3.5\lib\site-packages\tensorflow\python\training\input.py", line 922, in batch
    name=name)
  File "C:\Program Files\Python 3.5\lib\site-packages\tensorflow\python\training\input.py", line 716, in _batch
    dequeued = queue.dequeue_many(batch_size, name=name)
  File "C:\Program Files\Python 3.5\lib\site-packages\tensorflow\python\ops\data_flow_ops.py", line 457, in dequeue_many
    self._queue_ref, n=n, component_types=self._dtypes, name=name)
  File "C:\Program Files\Python 3.5\lib\site-packages\tensorflow\python\ops\gen_data_flow_ops.py", line 1342, in _queue_dequeue_many_v2
    timeout_ms=timeout_ms, name=name)
  File "C:\Program Files\Python 3.5\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "C:\Program Files\Python 3.5\lib\site-packages\tensorflow\python\framework\ops.py", line 2630, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "C:\Program Files\Python 3.5\lib\site-packages\tensorflow\python\framework\ops.py", line 1204, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

OutOfRangeError (see above for traceback): FIFOQueue '_1_create_inputs/batch/fifo_queue' is closed and has insufficient elements (requested 10, current size 0)
         [[Node: create_inputs/batch = QueueDequeueManyV2[component_types=[DT_FLOAT, DT_UINT8], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](create_inputs/batch/fifo_queue, create_inputs/batch/n)]]

**Comment by John1231983** [comment]
NewRandomAccessFile failed to Create/Open: E:\Data\VOC_data\VOC\VOCdevkit\VOC2012/SegmentationClassAug/2008_003519.png
Please check your path to dataset and folder aug

**Comment by ShaneTsui** [comment]
@John1231983 
Many thanks! 
Things turned out to be that I didn't have the complete VOC2012 dataset.
And for anyone later who may also run into such problem, here's a download link for 'SegmentationClassAug' dataset：https://www.dropbox.com/s/oeu149j8qtbs1x0/SegmentationClassAug.zip?dl=0
