### ISSUE TITLE
NotFoundError (see above for traceback): Tensor name 

### ISSUE THREAD

**Issue by ygjwd12345** [zhengyang-wang/Deeplab-v2--ResNet-101--Tensorflow#59]
2019-02-22 10:56:17.701864: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 AVX512F FMA
2019-02-22 10:56:17.878325: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1105] Found device 0 with properties: 
name: TITAN Xp major: 6 minor: 1 memoryClockRate(GHz): 1.582
pciBusID: 0000:17:00.0
totalMemory: 11.90GiB freeMemory: 11.74GiB
2019-02-22 10:56:17.878369: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1195] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: TITAN Xp, pci bus id: 0000:17:00.0, compute capability: 6.1)
-----------build encoder: res101-----------
after start block: (5, 129, 129, 64)
after block1: (5, 129, 129, 256)
after block2: (5, 65, 65, 512)
after block3: (5, 65, 65, 1024)
after block4: (5, 65, 65, 2048)
-----------build decoder-----------
after aspp block: (5, 65, 65, 21)
Traceback (most recent call last):
  File "/home/ygl/anaconda3/envs/MaskRCNN/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1350, in _do_call
    return fn(*args)
  File "/home/ygl/anaconda3/envs/MaskRCNN/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1329, in _run_fn
    status, run_metadata)
  File "/home/ygl/anaconda3/envs/MaskRCNN/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: Tensor name "resnet_v1_101/block1/unit_1/bottleneck_v1/conv1/BatchNorm/beta" not found in checkpoint files ./deeplab_resnet_init.ckpt
         [[Node: save_1/RestoreV2 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save_1/Const_0_0, save_1/RestoreV2/tensor_names, save_1/RestoreV2/shape_and_slices)]]
         [[Node: save_1/RestoreV2_484/_99 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_1142_save_1/RestoreV2_484", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 82, in <module>
    tf.app.run()
  File "/home/ygl/anaconda3/envs/MaskRCNN/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 124, in run
    _sys.exit(main(argv))
  File "main.py", line 76, in main
    getattr(model, args.option)()
  File "/media/ygl/深度学习/myjupyter/humanparsing/Deeplab-v2--ResNet-101--Tensorflow/model.py", line 42, in train
    self.load(self.loader, self.conf.pretrain_file)
  File "/media/ygl/深度学习/myjupyter/humanparsing/Deeplab-v2--ResNet-101--Tensorflow/model.py", line 393, in load
    saver.restore(self.sess, filename)
  File "/home/ygl/anaconda3/envs/MaskRCNN/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1686, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/home/ygl/anaconda3/envs/MaskRCNN/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 895, in run
    run_metadata_ptr)
  File "/home/ygl/anaconda3/envs/MaskRCNN/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1128, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/ygl/anaconda3/envs/MaskRCNN/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1344, in _do_run
    options, run_metadata)
  File "/home/ygl/anaconda3/envs/MaskRCNN/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1363, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.NotFoundError: Tensor name "resnet_v1_101/block1/unit_1/bottleneck_v1/conv1/BatchNorm/beta" not found in checkpoint files ./deeplab_resnet_init.ckpt
         [[Node: save_1/RestoreV2 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save_1/Const_0_0, save_1/RestoreV2/tensor_names, save_1/RestoreV2/shape_and_slices)]]
         [[Node: save_1/RestoreV2_484/_99 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_1142_save_1/RestoreV2_484", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]

Caused by op 'save_1/RestoreV2', defined at:
  File "main.py", line 82, in <module>
    tf.app.run()
  File "/home/ygl/anaconda3/envs/MaskRCNN/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 124, in run
    _sys.exit(main(argv))
  File "main.py", line 76, in main
    getattr(model, args.option)()
  File "/media/ygl/深度学习/myjupyter/humanparsing/Deeplab-v2--ResNet-101--Tensorflow/model.py", line 36, in train
    self.train_setup()
  File "/media/ygl/深度学习/myjupyter/humanparsing/Deeplab-v2--ResNet-101--Tensorflow/model.py", line 256, in train_setup
    self.loader = tf.train.Saver(var_list=restore_var)
  File "/home/ygl/anaconda3/envs/MaskRCNN/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1239, in __init__
    self.build()
  File "/home/ygl/anaconda3/envs/MaskRCNN/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1248, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/home/ygl/anaconda3/envs/MaskRCNN/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1284, in _build
    build_save=build_save, build_restore=build_restore)
  File "/home/ygl/anaconda3/envs/MaskRCNN/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 765, in _build_internal
    restore_sequentially, reshape)
  File "/home/ygl/anaconda3/envs/MaskRCNN/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 428, in _AddRestoreOps
    tensors = self.restore_op(filename_tensor, saveable, preferred_shard)
  File "/home/ygl/anaconda3/envs/MaskRCNN/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 268, in restore_op
    [spec.tensor.dtype])[0])
  File "/home/ygl/anaconda3/envs/MaskRCNN/lib/python3.6/site-packages/tensorflow/python/ops/gen_io_ops.py", line 1031, in restore_v2
    shape_and_slices=shape_and_slices, dtypes=dtypes, name=name)
  File "/home/ygl/anaconda3/envs/MaskRCNN/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/ygl/anaconda3/envs/MaskRCNN/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3160, in create_op
    op_def=op_def)
  File "/home/ygl/anaconda3/envs/MaskRCNN/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1625, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

NotFoundError (see above for traceback): Tensor name "resnet_v1_101/block1/unit_1/bottleneck_v1/conv1/BatchNorm/beta" not found in checkpoint files ./deeplab_resnet_init.ckpt
         [[Node: save_1/RestoreV2 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save_1/Const_0_0, save_1/RestoreV2/tensor_names, save_1/RestoreV2/shape_and_slices)]]
         [[Node: save_1/RestoreV2_484/_99 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_1142_save_1/RestoreV2_484", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]

**Comment by VicQwz** [comment]
同样的问题，楼主你怎么解决的

**Comment by ygjwd12345** [comment]
@VicQwz 这个问题主要是显存不够 你可以把batch=2. 或者你把input size改低点,我256*256 batch可以跑到10张.

**Comment by VicQwz** [comment]
> @VicQwz 这个问题主要是显存不够 你可以把batch=2. 或者你把input size改低点,我256*256 batch可以跑到10张.

行，我试试
