### ISSUE TITLE
only can train 2images

### ISSUE THREAD

**Issue by ygjwd12345** [zhengyang-wang/Deeplab-v2--ResNet-101--Tensorflow#60]
2019-03-01 15:27:08.090661: W tensorflow/core/common_runtime/bfc_allocator.cc:271] *___________________________________________________________________________________________________
2019-03-01 15:27:08.090706: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at constant_op.cc:169 : Resource exhausted: OOM when allocating tensor with shape[1024,1024,1024,21] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
Traceback (most recent call last):
  File "main.py", line 82, in <module>
    tf.app.run()
  File "/home/ygl/anaconda3/envs/fakeface/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "main.py", line 76, in main
    getattr(model, args.option)()
  File "/media/ygl/深度学习/myjupyter/humanparsing/Deeplab-v2--ResNet-101--Tensorflow/model.py", line 38, in train
    self.sess.run(tf.global_variables_initializer())
  File "/home/ygl/anaconda3/envs/fakeface/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/home/ygl/anaconda3/envs/fakeface/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/ygl/anaconda3/envs/fakeface/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1328, in _do_run
    run_metadata)
  File "/home/ygl/anaconda3/envs/fakeface/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 341, in __init__
    def __init__(self, node_def, op, message):

**Comment by zhengyang-wang** [comment]
"OOM when allocating tensor" indicated that your GPU memory has run out.
